dist: xenial
sudo: true
branches:
  only:
    - master
    - dev
services: mongodb
language: node_js
nodejs:
  - "12"
  - "lts/*"
before_install:
  - yarn install --ignore-optional --silent
cache:
  yarn: true
  directories:
    - ~/.cache
notifications:
  email: false
