version: "3.7"
services:
  client:
    container_name: p2srw_client
    build:
      context: ./p2s-frontend
      args:
        - host
        - port
    ports:
      - 80:80
    links:
      - server
    restart: always
    tty: true
  server:
    container_name: p2srw_server
    build:
      context: ./p2s-backend
      args:
        - envvar
        - db
        - host
        - port
    ports:
      - ${PORT}:${PORT}
    links:
      - db
    restart: always
    tty: true
  db:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
